# Generated by Django 4.1.7 on 2023-04-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SerializerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
